### ISSUE TITLE
Can no longer use /global /local /clan to change channels

### ISSUE THREAD

**Issue by Dagothur** [oscarpedrero/ChatLineColorMod#3]
Without the mod installed you can type /global to change the active chat channel to global. With the mod installed it seems you must use tab to cycle to the channel you want (whispers excepted).

**Comment by oscarpedrero** [comment]
I will review it for the next version of the mod.

**Comment by oscarpedrero** [comment]
@Dagothur A new version is now available in which you can disable only the channel name to have the functionality of being able to change channel with command
