### ISSUE TITLE
Allow a button or slash command to clear the chat

### ISSUE THREAD

**Issue by Dagothur** [oscarpedrero/ChatLineColorMod#7]
Very cool feature to clean the chat! It would be awesome if we had more agency on when the chat clears via a slash command or button.

**Comment by ChevalierNumerique** [comment]
Yes we need it

**Comment by oscarpedrero** [comment]
Added a button to delete the chat every time you hover in the chat window in last version ;)

![alt text](https://github.com/oscarpedrero/ChatLineColorMod/blob/master/imgs/clearbutton.jpg?raw=true)
